import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { getAllProjects,getProjectBySlug } from "@/lib/projects";

export function generateStaticParams(){return getAllProjects().map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getProjectBySlug(slug);return p?{title:p.title,description:p.description}:{};}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=getProjectBySlug(slug);if(!p)notFound();return <><Header/><main className="subpage"><section className="case-hero"><div className="case-hero-copy"><p className="eyebrow">Retrospective / {p.date}</p><h1 className="project-title">{p.title}</h1><p className="case-deck">{p.tagline}</p><div className="case-meta"><span>{p.role}</span>{p.technologies.map(t=><span key={t}>[{t}]</span>)}</div></div><div className="case-hero-art" aria-hidden="true"><div className="impossible-frame"><div className="impossible-frame frame-b"><div className="impossible-frame frame-c"><div className="impossible-frame frame-d"><span>{p.title.slice(0,2)}</span></div></div></div></div></div></section><section className="case-body"><aside><p>Project<br/>{p.title}</p><p>Role<br/>{p.role}</p><p>Status<br/>Completed / evolving</p></aside><article><p className="eyebrow">01 / The premise</p><h2>{p.question}</h2><p>{p.description}</p><p className="eyebrow">02 / What took shape</p><ul>{p.highlights.map(h=><li key={h}>{h}</li>)}</ul><p className="eyebrow">03 / Looking back</p><h2>The useful residue.</h2><p>{p.reflection}</p><div className="case-links"><a className="brutal-button" href={p.url} target="_blank" rel="noreferrer">Visit project <span>↗</span></a><Link className="brutal-button" href="/work">Back to archive</Link></div></article></section></main><Footer/></>}
