import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

const roles=[
  {period:"2023 — NOW",title:"Escherbridge LLC",role:"Founder / AI Solutions Architect",copy:"End-to-end product delivery for startups and specialist teams. The practice has produced AI-powered healthcare and project platforms, agent integrations, distributed data designs, and the independent systems collected in this archive."},
  {period:"2023 — NOW",title:"Idaho Power",role:"Senior Application Development Analyst",copy:"Business-critical C#/.NET systems, Azure Synapse and Microsoft Fabric reporting and forecasting frameworks, reusable UI and API components, and customer-facing applications. The work sharpened a practice of making complex enterprise systems operable and durable."},
  {period:"2022 — 2023",title:"System Tech Inc",role:"Full-stack software developer",copy:"React and Express applications delivered in close collaboration with designers and developers, including crowdfunding and management suites where product behavior and system performance had to advance together."},
  {period:"2018 — 2022",title:"Earlier technical work",role:"Developer / creative technologist",copy:"Cross-platform Node.js, Flutter, and AWS applications; a behavioral-health data collection prototype; therapeutic VR environments; WebGL volume rendering; web consulting; and IT."},
];

export default function ExperiencePage(){return <><Header/><main className="subpage"><section className="experience-hero"><p className="eyebrow">Experience / selected reflections</p><h1>Practice<br/><em>over title.</em></h1><p>Eight years of full-stack engineering across enterprise platforms, independent products, AI systems, and creative technology. This is less a ladder than a set of recurring questions about how useful systems get made.</p></section><section className="experience-grid">{roles.map(r=><article key={r.title}><time>{r.period}</time><div><h2>{r.title}</h2><h3>{r.role}</h3></div><p>{r.copy}</p></article>)}</section><section className="principles"><p className="eyebrow">What persists</p><h2>Three working principles</h2><div><article><span>01</span><h3>Own the whole path</h3><p>Requirements, architecture, interface, implementation, and deployment are one connected design problem.</p></article><article><span>02</span><h3>Make complexity inspectable</h3><p>Strong tools reveal state, boundaries, and consequences without asking the user to become the system.</p></article><article><span>03</span><h3>Use experiments as instruments</h3><p>A prototype is most valuable when it clarifies the question, not only when it resembles a finished product.</p></article></div></section></main><Footer/></>}
